@ECHO OFF
SETLOCAL
SET XSLTC="C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\xsltc.exe"
%XSLTC% /settings:dtd /out:STELLAR.Xsl.dll SKOS_CONCEPTSCHEMES.xslt SKOS_CONCEPTS.xslt CLAROS_OBJECTS.xslt ECRM_PERIODS.xslt CRMEH_GROUPS.xslt CRMEH_CONTEXTS.xslt CRMEH_FINDS.xslt CRMEH_SAMPLES.xslt CRMEH_SAMPLE_MEASUREMENTS.xslt CRMEH_INVESTIGATION_PROJECTS.xslt
ENDLOCAL

PAUSE
